version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: cargo
    directory: /mobile_v2_hasher
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
